### ISSUE TITLE
Object renaming issue

### ISSUE THREAD

**Issue by DenisNedvigok** [objecthub-io/ObjectHub#248] opened 2017-06-27 19:19 UTC
What: when you rename object new name does not appears in “My Objects” tab
Browser used: Google Chrome Version 58.0.3029.110 (64-bit)
How to perform:

- Create object in “My Objects” tab
- Rename object
- Review object’s name in “My Objects tab"

**Comment by objecthub-io** [comment] 2017-06-27 22:52
Thank you for reporting this issue.

We could confirm it and will address it in a coming update.

**Comment by objecthub-io** [comment] 2017-06-27 23:11
Duplicate of #245.

**Closed as completed by objecthub-io** 2017-06-27 23:11 UTC
