### ISSUE TITLE
Sometimes My Objects page not loaded in browser

### ISSUE THREAD

**Issue by mxro** [objecthub-io/ObjectHub#129] opened 2017-01-28 05:11 UTC
Exception reported:

```
Exception reported: Unauthorized: Insufficient authorization for database operation.
baseJs.js:71 java.lang.Exception: Unauthorized: Insufficient authorization for database operation.<br />
Unknown.vM(0.js@386)<br/>
Unknown.v(0.js@137)<br/>
Unknown.Dy(0.js@316)<br/>
Unknown._.eb(0.js@241)<br/>
Unknown.yy(0.js@313)<br/>
Unknown.xu(0.js@68)<br/>
Unknown._.w(0.js@414)<br/>
Unknown._.O(0.js@210)<br/>
Unknown._.O(0.js@314)<br/>
Unknown._.eb(0.js@433)<br/>
Unknown.Dy(0.js@287)<br/>
Unknown._.eb(0.js@474)<br/>
Unknown.cs(0.js@111)<br/>
Unknown.it(0.js@308)<br/>
Unknown._.F(0.js@377)<br/>
```

**Comment by objecthub-io** [comment] 2017-02-15 22:06
Was caused by issue in Authorization Cache which is now fixed.

**Closed as completed by objecthub-io** 2017-02-15 22:06 UTC
