### ISSUE TITLE
Search in Repository does not work as expected

### ISSUE THREAD

**Issue by DenisNedvigok** [objecthub-io/ObjectHub#266] opened 2017-07-03 21:00 UTC
When you try to search for some non-existing object and then try to search for some existing object in a Repository no objects are shown in search results. It takes a page refresh to make the search work again.
Please refer images for more info.
![step1](https://user-images.githubusercontent.com/12463408/27807763-a139fbda-604b-11e7-94b0-e6f7ea46b4bc.png)
![step2](https://user-images.githubusercontent.com/12463408/27807765-a3495628-604b-11e7-92d2-4cf53346b66c.png)
![step3](https://user-images.githubusercontent.com/12463408/27807767-a5549694-604b-11e7-87d8-cf49c515e1be.png)

**Comment by objecthub-io** [comment] 2017-07-05 07:51
Thank you for reporting this issue.

We can confirm it. Marking it as duplicate of #260.

**Closed as completed by objecthub-io** 2017-07-05 07:51 UTC
